## for miniProject

version: '3.8'

# docker volume 사용
volumes:
  mysql-db:
    external: true
    name: mysql-db
  
networks:
  shop-network:
    name: shop-network

services:
  
  web:
    container_name: website
    image: eeunnii/shop:ver1
    networks:
      - shop-network
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    # db콘이 먼저 만들어지고 그 다음에 web콘 생성
    environment:
      spring_datasource_hikari_driver-class-name: com.mysql.cj.jdbc.Driver
      spring_datasource_hikari_jdbc-url: jdbc:mysql://mysqldb:3307/shopper?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      spring_datasource_hikari_username: shop
      spring_datasource_hikari_password: shop
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    links:
      -  mysqldb


  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    networks:
      - shop-network
    ports:
      - 3307:3306
    volumes: 
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: shop
      MYSQL_DATABASE : shopper
      MYSQL_USER : shop
      MYSQL_PASSWORD : shop
      TZ: Asia/Seoul
      

